# Build Stage
FROM microsoft/aspnetcore-build:2 AS build-env

WORKDIR /web

COPY . .

RUN dotnet restore DeliveryService.MessageContracts/DeliveryService.MessageContracts.csproj
RUN dotnet restore DeliveryService.Registration.Web/DeliveryService.Registration.Web.csproj

RUN dotnet publish DeliveryService.MessageContracts/DeliveryService.MessageContracts.csproj -o /publish
RUN dotnet publish DeliveryService.Registration.Web/DeliveryService.Registration.Web.csproj -o /publish

# Runtime Image Stage
FROM microsoft/aspnetcore:2
WORKDIR /publish
COPY --from=build-env /publish .
ENTRYPOINT ["dotnet", "DeliveryService.Registration.Web.dll"]